[env:g0b1_cube]
platform = ststm32
board = nucleo_g0b1re
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_type = debug
debug_speed = 1000
debug_init_break = main
build_flags =
  -DSTM32G0B1xx