[env:custom_g0b1_arduino]
platform = ststm32
board = nucleo_g0b1re
framework = arduino
upload_protocol = dfu
debug_tool = stlink

; Adding this so you are ready for standard serial debugging
monitor_speed = 115200

build_flags = 
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D USBD_VID=0x0483
  -D USBD_PID=0x5740
  -D USB_MANUFACTURER="\"CustomBoard\""
  -D USB_PRODUCT="\"STM32G0B1_CDC\""
  -D HAL_PCD_MODULE_ENABLED